# Default hyper-parameters for training
batch_size: 64
learning_rate: 1e-4
# Discount factor for future rewards.
gamma: 0.995
buffer_size: 100000
train_steps: 1000000
checkpoint_freq: 1000
exploration_fraction: 0.2
exploration_final_eps: 0.02
priority_alpha: 0.6
priority_beta: 0.4
priority_beta_increment: 0.001
priority_eps: 1.0e-6
