# Default hyper-parameters for training
batch_size: 32
learning_rate: 3e-4
gamma: 0.99
buffer_size: 100000
train_steps: 2000000
checkpoint_freq: 10000
hidden_sizes: [256, 256]
dueling: true
double_q: true
